name: build flannel

on: [push, pull_request]

env:
  GO_VERSION: "1.21"
  LINUX_ARCHES: "amd64 arm arm64 s390x ppc64le riscv64"
  REPOSITORY: flannel/flannel

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: set tag 
        run: echo "GIT_TAG=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REPOSITORY }}
          flavor: latest=false
          tags: |
            type=ref, event=branch

      - name: Build multi-arch Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: images/Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64,linux/arm,linux/s390x,linux/ppc64le,linux/riscv64
          tags: ${{ steps.meta.outputs.tags }}
          build-args: TAG=${{ env.GIT_TAG }}

      - name: build for windows
        run: make dist/flanneld.exe
  
  